version: '3'

services:
  react:
    build: 
      context: .
      dockerfile: ./docker/react.Dockerfile
    #stdin_open: true
    #tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: >    
      sh -c "ls -ls && yarn start" 
    volumes:
      - ./react/src:/react/src
      - ./.env:/react/.env.development
    ports:
      - "2000:3000"
